#
# docker-compose.yml
#
master:
    image: docker/jenkins
    environment:
        JAVA_OPTS: "-Djava.awt.headless=true"
        JAVA_OPTS: "-Xmx2g"
        JAVA_OPTS: "-Xms1g"
    ports:
        - "50000:50000"
        - "8080:8080"
    volumes:
        - ./jenkins:/var/jenkins_home
jenkins_ruby:
    image: jenkins/node-ruby
seleniumhub:
    image: selenium/hub
    ports:
        - "4444:4444"
    environment:
        JAVA_OPTS: -Xmx2g
        JAVA_OPTS: -Xms1g
browsermob:
    image: browsermob/node
    ports:
        - "9000:9000"
        - "8081-8181:8081-8181"
    environment:
        JAVA_OPTS: -Xmx2g
        JAVA_OPTS: -Xms1g
chrome_node:
    image: selenium/node-chrome
    ports:
        - "5900"
    links:
        - seleniumhub:hub
firefox_node:
    image: selenium/node-firefox
    ports:
        - "5900"
    links:
        - seleniumhub:hub
elasticsearch:
    image: docker/elasticsearch
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
        - "9200:9200"
logstash:
    image: docker/logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
        - ./docker-elk/logstash/config:/etc/logstash/conf.d
    ports:
        - "5000:5000"
    links:
        - elasticsearch
kibana:
    image: docker/kibana
    ports:
        - "5601:5601"
    links:
        - elasticsearch
redis:
    image: docker/redis
    ports:
      - "6379:6379"
    links:
      - logstash
